### ISSUE TITLE
ERROR: Could not load file or assembly System.Net.Sockets

### ISSUE THREAD

**Issue by iAsure** [Flowseal/MegabonkTwitchIntegration#2]
Hi! I keep getting this error constantly and the mod doesn't work for me

[Error  :Il2CppInterop] Exception in IL2CPP-to-Managed trampoline, not passing it to il2cpp: System.IO.FileNotFoundException: Could not load file or assembly 'System.Net.Sockets, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.

**Comment by Flowseal** [comment]
Have you installed BepInEx 6.0.738 from there?
https://thunderstore.io/c/megabonk/p/BepInEx/BepInExPack_IL2CPP/

**Comment by iAsure** [comment]
> Have you installed BepInEx 6.0.738 from there? https://thunderstore.io/c/megabonk/p/BepInEx/BepInExPack_IL2CPP/

Yes, exactly that version `BepInEx-BepInExPack_IL2CPP-6.0.738.zip`

**Comment by Flowseal** [comment]
Install the latest .NET Runtime 8 and try again:
https://dotnet.microsoft.com/en-us/download/dotnet/8.0

Or the direct link:
https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-8.0.20-windows-x64-installer

The main problem that mod built with .NET 8, while dlls provided by bepinex are for .NET 6
I will fix it in the next release, but for know it should be fixed with installing .NET 8

**Comment by iAsure** [comment]
@Flowseal I already had version 9 installed when the error occurred. Now I have installed version 8, and the problem persists

**Comment by Flowseal** [comment]
> [@Flowseal](https://github.com/Flowseal) I already had version 9 installed when the error occurred. Now I have installed version 8, and the problem persists

Try please this version (built with .net6)

[TwitchIntegration.zip](https://github.com/user-attachments/files/22671251/TwitchIntegration.zip)

**Comment by iAsure** [comment]
It works! thanks!

**Comment by NanobotZ** [comment]
Hi, could you push the .NET 6 version to Thunderstore? Someone else in Megabonk discord had the same problem, NET6 version worked flawlessy for them.

**Comment by Flowseal** [comment]
> Hi, could you push the .NET 6 version to Thunderstore? Someone else in Megabonk discord had the same problem, NET6 version worked flawlessy for them.

done
